services:
  api-gateway:
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
    ports:
      - "5001:5001"

  auth-service:
    build:
      context: .
      dockerfile: ./apps/auth-service/Dockerfile
    ports:
      - "5002:5002"

  user-service:
    build:
      context: .
      dockerfile: ./apps/user-service/Dockerfile
    ports:
      - "5003:5003"

  management-service:
    build:
      context: .
      dockerfile: ./apps/management-service/Dockerfile
    ports:
      - "5004:5004"

  notification-service:
    build:
      context: .
      dockerfile: ./apps/notification-service/Dockerfile
    ports:
      - "5006:5006"
